base_config: 'configs/channel_vdsr_32_64/base.ram.yml'


teacher_model:
  name: 'channel_vdsr_teacher'
  params:
    scale: 2
    n_colors: 1
    m: 8
    k: 1
    encoder: lcscc


student_model:
  name: 'de_channel_vdsr_student'
  params:
    scale: 2
    n_colors: 1
    initialize_from:
      - './results/channel_vdsr_32_64/base_de_channel_vdsr_student/checkpoint/'
    modules_to_initialize:
      - - 'upsampler'
        - 'input_layer'
        - 'residual_layer_0'
        - 'residual_layer_1'
        - 'residual_layer_2'
        - 'residual_layer_3'
        - 'residual_layer_4'
        - 'residual_layer_5'
        - 'residual_layer_6'
        - 'residual_layer_7'
        - 'output_layer'
    vid_info:
      - 'residual_layer_0:None'
      - 'residual_layer_1:None'
      - 'residual_layer_2:None'
      - 'residual_layer_3:None'
      - 'residual_layer_4:None'
      - 'residual_layer_5:None'
      - 'residual_layer_6:None'
      - 'residual_layer_7:None'



train:
  batch_size: 16
  num_epochs: 1000
  teacher_dir: ''
  student_dir: ''


eval:
  batch_size: 1


scheduler:
  name: 'cosine'
  params:
    T_max: 1000
    eta_min: 0.00001


optimizer:
  name: adam
  params:
    lr: 0.001


loss:
  name: 'vid_loss'
  params:
    reduction: 'mean'
    lambda1: 1
    lambda2: 0.000001
    pdf: laplace


visualizer:
  name: 'step2'


gpu: 0

