base_config: 'configs/vdsr_base/base.ram.yml'

teacher_model:
  name: 'vdsr_adder_base_student'
  params:
    scale: 2
    n_colors: 1
    m: 4
    k: 1
    encoder:


train:
  batch_size: 16
  num_epochs: 1000
  teacher_dir: ''


eval:
  batch_size: 1


scheduler:
  name: 'cosine'
  params:
    T_max: 1000
    eta_min: 0.00001


optimizer:
  name: adam
  params:
    lr: 0.0001
#  gradient_clip: 0.25


loss:
  name: 'l1loss'
  params:
    reduction: 'mean'



visualizer:
  name: 'step2'


gpu: 0

