base_config: 'configs/self_deeper_fsrcnn_32_64/base.ram.yml'


teacher_model:
  name: 'self_fsrcnn_teacher'
  params:
    scale: 2
    n_colors: 1
    m: 4
    k: 1
    encoder: lcscc


student_model:
  name: 'self_fsrcnn_student_l2_base'
  params:
    scale: 2
    n_colors: 1
    initialize_from:

    modules_to_initialize:

    vid_info:
      - 'expanding:None'


train:
  batch_size: 16
  num_epochs: 1000
  teacher_dir: ''
  student_dir: ''


eval:
  batch_size: 1


scheduler:
  name: 'cosine'
  params:
    T_max: 1000
    eta_min: 0.00000001


optimizer:
  name: adam
  params:
    lr: 0.000001


loss:
  name: 'vid_loss_l2'
  params:
    reduction: 'mean'
    lambda1: 1
    lambda2: 0.000001
    pdf: laplace


visualizer:
  name: 'step2'


gpu: 0


