base_config: 'configs/conv_vdsr_32_64/base.ram.yml'


teacher_model:
  name: 'vdsr_teacher'
  params:
    scale: 2
    n_colors: 1
    m: 12
    k: 1
    encoder: lcscc


student_model:
  name: 'vdsr_student'
  params:
    scale: 2
    n_colors: 1
    initialize_from:
      - 'results/conv_vdsr_32_64/vdsr_teacher/checkpoint/'
    modules_to_initialize:
      - - 'upsampler'
        - 'input_layer'
        - 'residual_layer_0'
        - 'residual_layer_1'
        - 'residual_layer_2'
        - 'residual_layer_3'
        - 'residual_layer_4'
        - 'residual_layer_5'
        - 'residual_layer_6'
        - 'residual_layer_7'
        - 'residual_layer_8'
        - 'residual_layer_9'
        - 'residual_layer_10'
        - 'residual_layer_11'
        - 'output_layer'
    vid_info:



train:
  batch_size: 8
  num_epochs: 1000
  teacher_dir: ''
  student_dir: ''


eval:
  batch_size: 1


scheduler:
  name: 'cosine'
  params:
    T_max: 1000
    eta_min: 0.00001


optimizer:
  name: adam
  params:
    lr: 0.001


loss:
  name: 'vid_loss'
  params:
    reduction: 'mean'
    lambda1: 1
    lambda2: 0.000001
    pdf: laplace


visualizer:
  name: 'step2'


gpu: 0, 1


